name = "EvolvingDomains"
uuid = "f9bd8acb-b7a8-42b3-8348-bb9bbfd76943"
authors = ["Naoufel Cresson"]
version = "0.2.0"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapEmbedded = "8838a6a3-0006-4405-b874-385995508d5d"
LevelSetMethods = "ca3df947-0575-4ae6-b9a3-78df393a7451"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[sources]
LevelSetMethods = {rev = "e0bdd38", url = "https://github.com/maltezfaria/LevelSetMethods.jl"}

[extensions]
EvolvingDomainsMakieExt = "CairoMakie"


[compat]
CairoMakie = "0.15"
Gridap = "0.18"
GridapEmbedded = "0.9"
Printf = "1.11.0"
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
